# This workflow will upload a Python Package to Release asset
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Create Release

on:
  workflow_dispatch:

jobs:
  wheel:
    name: Build wheels on ${{ matrix.os }} python${{ matrix.python-version }} torch${{ matrix.pytorch-version }} cuda${{ matrix.cuda-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-22.04']
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        pytorch-version: ['2.7.0', '2.8.0', '2.9.0', '2.10.0', '2.11.0']
        cuda-version: ['12.6']
        exclude:
          - pytorch-version: '2.7.0'
            python-version: '3.14'
          - pytorch-version: '2.8.0'
            python-version: '3.14'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Linux Env
        if: ${{ runner.os == 'Linux' }}
        run: |
          bash -x .github/workflows/scripts/env.sh

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Install CUDA ${{ matrix.cuda-version }}
        run: |
          bash -x .github/workflows/scripts/cuda-install.sh ${{ matrix.cuda-version }} ${{ matrix.os }}

      - name: Clean APT cache
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install PyTorch ${{ matrix.pytorch-version }} with CUDA ${{ matrix.cuda-version }}
        run: |
          bash -x .github/workflows/scripts/pytorch-install.sh ${{ matrix.python-version }} ${{ matrix.pytorch-version }} ${{ matrix.cuda-version }}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Build wheel
        shell: bash
        run: |
          bash -x .github/workflows/scripts/cutlass-install.sh
          bash -x .github/workflows/scripts/build.sh ${{ matrix.python-version }} ${{ matrix.cuda-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ matrix.cuda-version }}
          path: ./wheelhouse/*.whl


  consolidate-wheels:
    needs: [wheel]
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Consolidate wheels into a single folder
        run: |
          mkdir -p consolidated_wheels
          find dist -name '*.whl' -exec cp {} consolidated_wheels/ \;
          ls -l consolidated_wheels

      - name: Upload consolidated wheels
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels
          path: consolidated_wheels
